version: '3'
services:
  mongodb:
    image: mongo:5.0
    volumes: 
      - ./initdb:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017  
    environment:
      - MONGO_PASSWORD:${MONGO_PASSWORD}  